package:
  name: pytracemalloc
  version: !!str 1.0

source:
  fn: pytracemalloc-1.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pytracemalloc/pytracemalloc-1.0.tar.gz
  md5: daabf259421ce1bf0229b2b0ac10de2d
#  patches:
   # List any patch files here
   # - fix.patch

build:
  features:
    - pytracemalloc

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pytracemalloc = pytracemalloc:main
    #
    # Would create an entry point called pytracemalloc that calls pytracemalloc.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - enable-pytracemalloc

  run:
    - python
    - enable-pytracemalloc

test:
  requires:
    - enable-pytracemalloc
  # Python imports
  imports:
    - tracemalloc

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pytracemalloc.readthedocs.org/
  license:  MIT License
  summary: 'Track memory allocations per Python file'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
