package:
  name: python
  version: 3.4.1_mmr

source:
  fn: Python-3.4.1.tar.xz
  url: https://www.python.org/ftp/python/3.4.1/Python-3.4.1.tar.xz

requirements:
  build:
    - openssl 1.0.1h
    - readline 6.2*_mmr
    - ncurses 5.9*_mmr
    - sqlite 3.8.4.1
    - system 5.8
    - tk 8.5.15
    - zlib 1.2.7

  run:
    - openssl 1.0.1h
    - readline 6.2*_mmr
    - ncurses 5.9*_mmr
    - sqlite 3.8.4.1
    - system 5.8
    - tk 8.5.15
    - zlib 1.2.7


build:
  number: 1

about:
  home: http://python.org
  license: psf
