package:
  name: python
  version: 2.7.9_mmr

source:
  fn: Python-2.7.9.tar.xz
  url: https://www.python.org/ftp/python/2.7.9/Python-2.7.9.tar.xz

requirements:
  build:
    - openssl 1.0.1j
    - readline 6.2*_mmr
    - ncurses 5.9*_mmr
    - sqlite 3.8.4.1
    - system 5.8
    - tk 8.5.15
    - zlib 1.2.7

  run:
    - openssl 1.0.1j
    - readline 6.2*_mmr
    - ncurses 5.9*_mmr
    - sqlite 3.8.4.1
    - system 5.8
    - tk 8.5.15
    - zlib 1.2.7


build:
  number: 2
  detect_binary_files_with_prefix: true

about:
  home: http://python.org
  license: psf
  summary: 'Python package for conda fixing the readline issue'
